### ISSUE TITLE
Error: image not found,but it does exist

### ISSUE THREAD

**Issue by shuizaola** [dongkwonjin/Eigenlanes#3]
CUDA_VISIBLE_DEVICES=1 nohup python main.py --run_mode train --pre_dir /home/Disk-2T/chedao/Eigenlanes-main/preprocessed/tusimple/ --dataset_dir /home/Disk-2T/chedao/Eigenlanes-main/Tusimple > tisimpletrain1.log 2>&1 &
[1] 28049
(chelane) caipeng@li-MS-7B96:/home/Disk-2T/caipeng_chedao/Eigenlanes-main/Modeling/tusimple/code$ tail -f tisimpletrain1.log
train start
/home/Disk-2Taipeng_chedao/Eigenlanes-main/Modeling/tusimple/code/networks/model.py:158: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  area[i] = mask[i].nonzero().shape[0]
/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/nn/_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/nn/_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
img iter 0 ==> 0313-1/50820/20
img iter 50 ==> 0313-1/43140/20
img iter 100 ==> 0313-1/6400/20
img iter 150 ==> 0313-2/42280/20
img iter 200 ==> 0313-1/5820/20
img iter 250 ==> 0313-2/8040/20

Average Loss : 0.060205, 0.027879, 0.026334, 0.686977, 1.284911, 0.057571, 0.004878, 0.066173, 0.354894, 
label distribution [80.7  0.   0.   0.   0.   0.   0.   1.8 14.5  2.9  0. ]

epoch 1

train start
/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/nn/functional.py:3118: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:143: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
img iter 0 ==> 0313-1/16760/20
img iter 50 ==> 0313-1/13680/20
img iter 100 ==> 0313-2/25200/20
img iter 150 ==> 0313-2/1055/20
img iter 200 ==> 0313-2/615/20
img iter 250 ==> 0313-2/6360/20

Average Loss : 0.050388, 0.021135, 0.007948, 0.073888, 0.403831, 0.031649, 0.004619, 0.039286, 0.174917, 
label distribution [79.8  0.   0.   0.   0.   0.   0.   2.5 14.9  2.8  0. ]

Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main()
  File "main.py", line 46, in main
    main_train(cfg, dict_DB)
  File "main.py", line 23, in main_train
    train_process.run()
  File "/home/Disk-2T/chedao/Eigenlanes-main/Modeling/tusimple/code/trains/train.py", line 135, in run
    self.validation()
  File "/home/Disk-2T/chedao/Eigenlanes-main/Modeling/tusimple/code/trains/train.py", line 115, in validation
    metric = self.test_process.run(self.model, mode='val')
  File "/home/Disk-2T/chedao/Eigenlanes-main/Modeling/tusimple/code/tests/test.py", line 23, in run
    for i, self.batch in enumerate(self.testloader):  # load batch data
  File "/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cp/anaconda3/envs/chelane/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/Disk-2T/chedao/Eigenlanes-main/Modeling/tusimple/code/datasets/dataset_tusimple.py", line 249, in __getitem__
    out.update(self.get_image(idx))
  File "/home/Disk-2T/chedao/Eigenlanes-main/Modeling/tusimple/code/datasets/dataset_tusimple.py", line 200, in get_image
    img = Image.open(self.cfg.dir['dataset'] + '/test_set/clips/{}.jpg'.format(self.datalist[idx])).convert('RGB')
  File "/home/caipeng/anaconda3/envs/chelane/lib/python3.8/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/Disk-2T/chedao/Eigenlanes-main/Tusimple/test_set/clips/0530/1492626760788443246_0/20.jpg'

**Comment by dongkwonjin** [comment]
Hi. Thank you for your interest.

Please check if the image path is correct.

You can download Tusimple dataset at https://github.com/TuSimple/tusimple-benchmark/issues/3.
